### ISSUE TITLE
Export HAR from mitmproxy

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/cyanoacrylate#1]
Currently, we're exporting the raw internal flow format from mitmproxy. But that is not very useful, there aren't really any other tools that can work with that.

Instead, we should export HAR files. There is a mitmproxy script for that purpose already: https://github.com/mitmproxy/mitmproxy/blob/main/examples/contrib/har_dump.py

The problem is that this script is not included in the mitmproxy distribution (it's a community-contributed example script not maintained by the core developers—though that may change in the future: https://github.com/mitmproxy/mitmproxy/issues/1477).

I'm not sure what the best way to handle that would be. It would be pretty unfortunate if the user had to manually download the script corresponding to their mitmproxy version and then provide the path as an option…

**Comment by zner0L** [comment]
The solution I am currently using is just asking the user to download the script. But I am now thinking about starting mitmproxy from a script (like so: https://stackoverflow.com/a/52130229)  and it would just be convenient to distribute the script in there… I know there is still the issue of an unclear license, though one could argue that the whole project is MIT licensed.
