### ISSUE TITLE
Use standard cache folder instead of `__dirname` for venv and mitmproxy scripts

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/cyanoacrylate#18]
Putting the venv and mitmproxy scripts into our `node_modules` folder (relative to `__dirname`) is unfortunately quite fragile. We've already had a fair amount of breakage due to this and while reviewing #17, I once again noticed this breaking.

For some bizarre reason, `__dirname` is `/home/benni/coding/JS/tweasel/cyanoacrylate/dist/src`, even though that folder doesn't exist (the built `index.js` is in `dist`, deleting that and the Parcel cache didn't help).

I propose that we instead put this stuff into the system cache folder using [global-cache-dir](https://www.npmjs.com/package/global-cache-dir). That feels more idiomatic, anyway.

Additional benefit: If we want to distribute a single executable at some point, there won't be a `node_modules` folder that we can write to, anyway.

What do you think, @zner0L?

**Comment by baltpeter** [comment]
One thing to consider: It's plausible that someone might delete this cache directory without re-running the `postinstall` script, which would break the module. This could already happen with the current implementation, but I feel like it's more likely if we use a cache directory.

Not too hard to work, around though: We can just check whether the necessary files exist and run the `postinstall` script otherwise.

**Comment by zner0L** [comment]
Yeah, that seems reasonable to me. I am just not sure where we would put this check. In `startAnalysis`?

**Comment by baltpeter** [comment]
> I am just not sure where we would put this check. In `startAnalysis`?

Yeah, that seems reasonable to me.

**Comment by baltpeter** [comment]
Actually, I went with `startTrafficCollection()`, since `startAnalysis()` isn't async and we only need those dependencies for the traffic collection.

**Comment by baltpeter** [comment]
This change has fixed the CLI for m.e

**Comment by baltpeter** [comment]
For some reason, Parcel breaks `os.platform` (it removes the import and replaces it with an undefined identifier, very helpful). But `process.platform` works.

**Comment by baltpeter** [comment]
Windows just really wants to annoy you, doesn't it. _Of course_, `PATH` entries are delimted by `;` instead of `:`. -.-
