### ISSUE TITLE
Use andromatic for `emulator` command

### ISSUE THREAD

**Issue by baltpeter** [tweaselORG/cyanoacrylate#22]
We expect the user to have an `emulator` command in the `PATH` here:

https://github.com/tweaselORG/cyanoacrylate/blob/886282d5550512f8a0a6c2529fcc9610642c5845/src/index.ts#L473

This currently isn't even documented. Instead, we should automatically install that using andromatic.

**Comment by baltpeter** [comment]
We should include that in the release. Implementing right now.

**Comment by zner0L** [comment]
Oh, I already released. Well, than we‘ll churn out another one, I guess.
