### ISSUE TITLE
Can't start traffic analysis: Starting mitmproxy failed after a timeout.

### ISSUE THREAD

**Issue by techware01** [tweaselORG/cyanoacrylate#43]
Hey, 
was trying to run this project to test an app and see how it works. 
Setting up an android emulator, installing an app etc. with tweasel-cli worked with not issue. 
But when it comes to traffic-recording the mitmproxy part fails for me:

```
file:///home/**/tweasel/node_modules/cyanoacrylate/dist/index.js:261
            if (e.name === "TimeoutError") throw new (0, $kYxtx$TimeoutError)("Starting mitmproxy failed after a timeout.");
                                                 ^

TimeoutError: Starting mitmproxy failed after a timeout.
    at file:///home/**/tweasel/node_modules/cyanoacrylate/dist/index.js:261:50
    at async startTrafficCollection (file:///home/**/tweasel/node_modules/cyanoacrylate/dist/index.js:258:9)
    at async file:///home/**/tweasel/test.js:25:5

Node.js v18.17.1
```

I already tried running the post install script for this project again to see if this brings any errors and checked the cache for the existence of python file. That works. 
But I couldn't find the .venv directory mentioned in https://github.com/tweaselORG/cyanoacrylate/issues/12.

Any ideas what I could do to get this running?

**Comment by techware01** [comment]
Hey, 
thank you very much for the detailed explanation. That brought me to the issue! 
Probably from earlier tests with mitmproxy I had some old CA files in `/home/$USER/.mitmproxy/` owned by root. 
When running your command as non root user it failed opening them. After deleting the directory it worked just fine.

**Comment by baltpeter** [comment]
Great, glad to hear that! I've opened #44 to see whether we can provide more helpful information if mitmproxy fails to start.
