### ISSUE TITLE
Stdout stream is not flushed deterministcally for mitmdump

### ISSUE THREAD

**Issue by zner0L** [tweaselORG/cyanoacrylate#5]
While trying to write a proper example I ran into an issue, where the program would timeout all the time while waiting for mitmproxy to start. After a lot of investigation, it turns out that the problem is detecting whether mitmproxy started already. Right now, we do this by waiting for the start text to appear in the output, e.g. "listening at". But this fails often, because the `stdout` stream is not flushed before the timeout runs out, if nothing new is added to the output, leaving the `awaitProcessStart` to timeout. I have not found a way to make `execa` to flush the stream earlier.

To resolve this, I either

- need a way to flush the stream earlier, to read the info at the start
- a different way to know mitmproxy is running

**Comment by baltpeter** [comment]
Oh yeah, I remember running into the same problem for the data safety label analysis. Probably something changed in mitmproxy since I originally wrote the code.

My "solution" back then was to increase the timeout to a ridiculous value, it did always flush after a fairly long time:

https://github.com/datenanfragen/android-data-safety-label-analysis/blob/e7cea9f5df4e0d212631760e04d784b8285eb7ed/src/traffic.ts#LL93C17-L93C91

**Comment by baltpeter** [comment]
> a different way to know mitmproxy is running

I mean, you could check that the port is closed beforehand and then wait for it to be opened after launching mitmproxy… But I'm not sure whether "port open" == "mitmproxy ready".

**Comment by zner0L** [comment]
Weirdly enough, if I add `process.stdout` in execa directly, it doesn't seem to have this flushing problem:

```
execa('mitmdump', ['-w', flowsOutputPath], { stdout: process.stdout });
```

However, for weird reasons we cannot just add our own streams into that to test if that would solve the problem (see https://github.com/sindresorhus/execa/issues/81).

**Comment by zner0L** [comment]
I think, the cleanest way to do this would be to write an addon for mitmproxy that emits the [lifecycle events](https://docs.mitmproxy.org/stable/api/events.html#LifecycleEvents) as IPC event on a socket. But this would be some additional work. What do you think, @baltpeter?

**Comment by zner0L** [comment]
This would also enable us to detect errors, such as a misconfigured TLS encryption.

**Comment by baltpeter** [comment]
I'm not happy about the added complexity, but I'll leave the decision to you. If you think that's the best way forward, that's fine. (Have you checked whether mitmproxy might have a similar feature in core already?)

**Comment by zner0L** [comment]
I don’t think it should be too complicated. IPC seems easy enough (though I worry about Windows): https://stackoverflow.com/questions/23804434/python-process-forked-by-nodejs-alternative-to-process-send-for-python

I’ll give it a try.

**Comment by zner0L** [comment]
Where should I put the addon? `src` seems wrong smh.

**Comment by baltpeter** [comment]
Can we make that a separate Python package that the user can install as a dependency with `pip` and so that it can be useful for others? Or would that be too annoying`

**Comment by zner0L** [comment]
Ok, so [this stackoverflow](https://stackoverflow.com/questions/73278018/node-js-ipc-between-a-python-parent-and-a-node-js-child) made me think using the node IPC funtions is easy, even though it is not offically supported. And it is very easy, in fact. I can just write to the correct file descriptor in python and the message is passed to the parent node process:

```python
import os

os.write(3, bytes('{"test" : "This is a test"}\n', "utf8"))
```
The parent looks like this:
```js
const { spawn, } = require('child_process');

const proc = spawn('python', ['./child.py'], {
    stdio: ['pipe', 'pipe', 'pipe', 'ipc'],
});
proc.on('message', (msg) => console.log(msg)); // { test: "This is a test" }
```

This is all fine and good on linux, but when it comes to Windows it is an entirely different and even less supported story. I am unsure if I should pursue this, whether we even want to support Windows or if I should just use sockets.

**Comment by zner0L** [comment]
Ok, having investigated a little more, I found out that nodejs [uses `libuv`](https://github.com/nodejs/node/blob/main/src/pipe_wrap.cc#L219) to create the pipes, which on Windows [creates a named pipe](https://docs.libuv.org/en/v1.x/pipe.html). This is somehow connected to the file descriptor in node which is OS-independent ([it is just iterated](https://github.com/nodejs/node/blob/main/lib/internal/child_process.js#L1036)) and which we do know. But I have no idea how `libuv` gets the pipe out of that again. nodejs calls `uv_pipe_open()`, so I guess that could do it. I was a little hopeful when I found https://github.com/saghul/pyuv, but this is no longer actively maintained  and fails to build (see https://github.com/saghul/pyuv/issues/270#issuecomment-925106097). 

So, having tried quite a lot, I think we will have to give up Windows support for now. I haven't tested the rest of the code on Windows, yet, anyway. I guess as a workaround we can also skip waiting for `mitmproxy` on Windows and just assume it started correctly if the process didn't fail, but I really dislike that.

**Comment by zner0L** [comment]
Because python package are really bad for distributing scripts, I don’t see a great way to distribute the addon, for now I just put it in a different repository: https://github.com/tweaselORG/mitmproxy_ipc_events_addon
